// Local encrypted vault. No network, telemetry, or persistent session key.
export const VAULT_KEY='entre.vault.v1';
const vaultEncoder=new TextEncoder(),vaultDecoder=new TextDecoder();
const vaultB64=bytes=>{const a=new Uint8Array(bytes);let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s)};
const vaultBytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const vaultRandom=n=>crypto.getRandomValues(new Uint8Array(n));
export function cryptoReady(){return !!globalThis.crypto?.subtle;}
async function vaultPasswordKey(password,salt,iterations){const k=await crypto.subtle.importKey('raw',vaultEncoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:vaultBytes(salt),iterations,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function vaultRawKey(bytes){return crypto.subtle.importKey('raw',bytes,'AES-GCM',true,['encrypt','decrypt']);}
async function vaultSeal(key,bytes,context){const iv=vaultRandom(12);return {iv:vaultB64(iv),data:vaultB64(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:vaultEncoder.encode(context)},key,bytes))};}
async function vaultOpen(key,box,context){return crypto.subtle.decrypt({name:'AES-GCM',iv:vaultBytes(box.iv),additionalData:vaultEncoder.encode(context)},key,vaultBytes(box.data));}
export function checkVault(v){if(!v||v.format!=='ENTRE-encrypted'||v.version!==1||typeof v.id!=='string'||v.id.length>80||v.iterations!==310000||typeof v.salt!=='string'||vaultBytes(v.salt).length!==16)throw Error('invalid');for(const field of ['password','recovery','payload']){const box=v[field];if(!box||typeof box.iv!=='string'||typeof box.data!=='string'||vaultBytes(box.iv).length!==12||box.data.length>7000000||vaultBytes(box.data).length<16)throw Error('invalid');}return v;}
export async function makeVault(password,data){const raw=vaultRandom(32),key=await vaultRawKey(raw),recoveryBytes=vaultRandom(32),recoveryCode=Array.from(recoveryBytes,b=>b.toString(16).padStart(2,'0')).join('').match(/.{8}/g).join('-');const v={format:'ENTRE-encrypted',version:1,id:vaultB64(vaultRandom(18)),iterations:310000,salt:vaultB64(vaultRandom(16))};v.password=await vaultSeal(await vaultPasswordKey(password,v.salt,v.iterations),raw,v.id+':password');v.recovery=await vaultSeal(await vaultRawKey(recoveryBytes),raw,v.id+':recovery');v.payload=await vaultSeal(key,vaultEncoder.encode(JSON.stringify(data)),v.id+':payload');return {vault:v,key,recoveryCode};}
export async function unlockVault(v,secret,recovery=false){checkVault(v);let wrapping;if(recovery){const code=secret.replace(/[\s-]/g,'').toLowerCase();if(!/^[0-9a-f]{64}$/.test(code))throw Error('access');wrapping=await vaultRawKey(Uint8Array.from(code.match(/../g),b=>parseInt(b,16)));}else wrapping=await vaultPasswordKey(secret,v.salt,v.iterations);const field=recovery?'recovery':'password';const key=await vaultRawKey(await vaultOpen(wrapping,v[field],v.id+':'+field));const data=JSON.parse(vaultDecoder.decode(await vaultOpen(key,v.payload,v.id+':payload')));return {key,data};}
export async function sealVault(v,key,data){return {...v,payload:await vaultSeal(key,vaultEncoder.encode(JSON.stringify(data)),v.id+':payload')};}
export async function changeVaultPassword(v,key,password){const next={...v,salt:vaultB64(vaultRandom(16))};next.password=await vaultSeal(await vaultPasswordKey(password,next.salt,next.iterations),await crypto.subtle.exportKey('raw',key),v.id+':password');return next;}
