import {createClient} from './vendor/supabase.js';
import {SUPABASE_URL,SUPABASE_KEY,APP_URL} from './config.js';
import {QUESTIONS,TOPICS,MODULES,DATES,DESIRE_OPTIONS,PATHS} from './data.js';
import {esc,errorText,agreementState,visibleRecords,privateImportPayload} from './cloud-model.js';
import {checkVault,unlockVault,makeVault} from './auth.js';
import {validate} from './store.js';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storageKey:'entre.cloud.auth.v1',flowType:'implicit'},global:{fetch:(url,options={})=>fetch(url,{...options,signal:options.signal||AbortSignal.timeout(18000)})}});
const $=s=>document.querySelector(s), modal=$('#modal'), body=$('#modal-body'), main=$('#main');
const button=(label,action,extra='',cls='secondary')=>`<button type="button" class="button ${cls}" data-action="${action}" ${extra}>${label}</button>`;
const input=(id,label,type='text',value='',extra='')=>`<label for="${id}">${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const textarea=(id,label,value='')=>`<label for="${id}">${label}<textarea id="${id}" maxlength="4000">${esc(value)}</textarea></label>`;
const privacyChoice=()=>`<label class="check-label"><input type="checkbox" id="share" ${members.length<2?'disabled':''}> Compartir este registro con mi pareja${members.length<2?' (vinculad primero las cuentas)':''}.</label><p class="help">Sin marcar: solo tu cuenta podrá verlo desde la app. Guardar lo enviará a Supabase. Puedes no guardarlo.</p>`;
let user=null,records=[],members=[],profiles=[],verified=false,route='hoy',busy=false,loading=false,recovery=false,started=false,dirty=false,toastTimer,channel,modalCleanup=null,generation=0,lastSync=0,question=null,questionFilter='all',questionLevel='all',adult=false;
let theme='dark';try{theme=localStorage.getItem('entre.cloud.theme')||'dark'}catch{}document.body.dataset.theme=theme;
const mine=()=>visibleRecords(records,user?.id,verified).filter(r=>r.owner_id===user?.id);
const visible=()=>visibleRecords(records,user?.id,verified);
const myName=()=>profiles.find(p=>p.user_id===user?.id)?.display_name||user?.user_metadata?.display_name||'Tú';
const partner=()=>members.find(m=>m.user_id!==user?.id);
const displayName=id=>profiles.find(p=>p.user_id===id)?.display_name||(id===user?.id?myName():'Tu pareja');
const fmt=d=>new Date(d).toLocaleDateString('es-ES',{day:'numeric',month:'short'});
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000)}
function close(force=false){if(!force&&dirty&&!confirm('Hay texto sin guardar. ¿Quieres cerrar y descartarlo?'))return false;if(modalCleanup)modalCleanup();modalCleanup=null;dirty=false;modal.close();body.innerHTML='';$('#modal-error').textContent='';return true}
function show(title,html){if(modalCleanup)modalCleanup();modalCleanup=null;dirty=false;body.innerHTML=`<h2 id="modal-title" tabindex="-1">${title}</h2>${html}`;$('#modal-error').textContent='';if(!modal.open)modal.showModal();$('#modal-title').focus();}
modal.addEventListener('cancel',e=>{e.preventDefault();close()});modal.addEventListener('input',e=>{if(!['find','question-topic','question-level'].includes(e.target.id))dirty=true});
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}});
async function task(fn){if(busy)return;busy=true;const controls=[...document.querySelectorAll('button,input,textarea,select')].map(b=>[b,b.disabled]);controls.forEach(([b])=>b.disabled=true);const er=modal.open?$('#modal-error'):$('#auth-error');if(er)er.textContent='Un momento…';try{await fn();if(er?.isConnected)er.textContent=''}catch(e){if(er?.isConnected)er.textContent=errorText(e);else toast(errorText(e))}finally{busy=false;controls.forEach(([b,disabled])=>b.disabled=disabled)}}
async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw error;return data}
function authScreen(title,text,content){document.body.classList.add('locked');$('.sidebar').hidden=true;$('.shell').hidden=true;$('#auth-root').hidden=false;$('#auth-root').innerHTML=`<div class="auth-layout"><section class="auth-story"><span class="brand">entre<span>•</span></span><div class="auth-art" aria-hidden="true"><i></i><i></i><span>un espacio<br>entre los dos.</span></div><p>CERCA, SIN DEJAR DE SER TÚ</p></section><section class="auth-card"><span class="eyebrow">CADA PERSONA, SU PROPIO ESPACIO</span><h1>${title}</h1><p class="auth-intro">${text}</p>${content}<p id="auth-error" class="error" role="alert"></p><div class="auth-footer">${button('Privacidad','privacy','','ghost')}<a href="local.html">Mis datos de la versión local</a></div></section></div>`;}
function welcome(step=0){const slides=[['Un momento<br>para <em>vosotros.</em>','Cómo llegas hoy, una pregunta para escucharos y acuerdos pequeños. Cada uno desde su móvil.'],['Sin notas.<br>Sin <em>presión.</em>','No es terapia ni un diagnóstico. Puedes responder, pasar o parar. Descansar no borra vuestro progreso.'],['Lo íntimo,<br>con <em>claridad.</em>','Tu correo y lo que decidas guardar se envían a Supabase. Tus reflexiones son privadas en la app. Solo se comparte con tu pareja lo que elijas. No es cifrado de extremo a extremo.']];if(step>2){login();return}authScreen(slides[step][0],slides[step][1],`<p class="help">${step+1} de 3 · Sin anuncios ni IA conectada.</p><div class="cloud-actions">${button('Continuar','welcome',`data-step="${step+1}"`,'')}${button('Saltar e iniciar sesión','login','','ghost')}</div>`)}
function login(mode='login'){
 const signup=mode==='register',recover=mode==='recover';authScreen(signup?'Tu cuenta.<br><em>Vuestro vínculo.</em>':recover?'Volver a<br><em>entrar.</em>':'Qué bien<br><em>tenerte aquí.</em>',signup?'Cada persona usa su propio correo. Después podréis vincularos mediante una invitación.':recover?'Te enviaremos un enlace para elegir otra contraseña.':'Entra con tu cuenta personal de ENTRE.',`<form id="auth-form" class="cloud-form">${signup?input('name','Nombre o apodo','text','','required maxlength="35" autocomplete="nickname"'):''}${input('email','Correo electrónico','email','','required autocomplete="email" maxlength="254"')}${!recover?input('password','Contraseña','password','','required minlength="12" maxlength="200" autocomplete="'+(signup?'new-password':'current-password')+'"'):''}${signup?`<p class="help">Al menos 12 caracteres. No pedimos teléfono, fecha de nacimiento ni redes sociales.</p><label class="check-label"><input id="privacy-consent" type="checkbox" required> Entiendo que mi cuenta y los registros que guarde se alojarán en Supabase.</label>`:''}<button class="button" type="submit">${signup?'Crear mi cuenta':recover?'Enviar enlace':'Entrar'}</button></form><div class="cloud-actions">${button(signup||recover?'Ya tengo cuenta':'Crear cuenta',signup||recover?'login':'register','','ghost')}${!recover?button('He olvidado la contraseña','recover','','ghost'):''}${!signup&&!recover?button('Reenviar confirmación','resend','','ghost'):''}</div>`);
 $('#auth-form').onsubmit=e=>{e.preventDefault();const email=$('#email').value.trim(),password=$('#password')?.value,name=$('#name')?.value.trim();task(async()=>{
 if(signup&&!name)throw {userMessage:'Escribe un nombre o apodo.'};
 if(recover){const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:APP_URL});if(error)throw error;$('#auth-error').textContent='';authScreen('Mira tu<br><em>correo.</em>','Si hay una cuenta con ese correo, recibirás un enlace para recuperar el acceso. Revisa también el spam.',button('Volver a entrar','login'));return}
 const {data,error}=signup?await sb.auth.signUp({email,password,options:{emailRedirectTo:APP_URL,data:{display_name:name}}}):await sb.auth.signInWithPassword({email,password});if(error)throw error;
 if(!data.session){authScreen('Un paso<br><em>más.</em>','Revisa tu correo para confirmar la cuenta. Si ya estabas registrado, puedes entrar o recuperar el acceso.',button('Volver a entrar','login'));return}await enter(data.session.user);
 })};
}
function newPassword(){authScreen('Un nuevo<br><em>acceso.</em>','Elige una contraseña distinta para tu cuenta.',`<form id="new-password-form" class="cloud-form">${input('new-password','Nueva contraseña','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}${input('repeat-password','Repite la contraseña','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}<button class="button" type="submit">Guardar contraseña</button></form>`);$('#new-password-form').onsubmit=e=>{e.preventDefault();task(async()=>{if($('#new-password').value!==$('#repeat-password').value)throw {userMessage:'Las contraseñas no coinciden.'};const {data,error}=await sb.auth.updateUser({password:$('#new-password').value});if(error)throw error;recovery=false;await enter(data.user);toast('Contraseña actualizada.')})}}
async function enter(u){if(!u||recovery)return;user=u;generation++;document.body.classList.remove('locked');$('#auth-root').hidden=true;$('#auth-root').innerHTML='';$('.sidebar').hidden=false;$('.shell').hidden=false;render();await refresh();if(channel)sb.removeChannel(channel);channel=sb.channel('entre-'+u.id).on('postgres_changes',{event:'*',schema:'public'},()=>refresh()).subscribe();}
async function rows(table){let all=[];for(let page=0;;page++){const {data,error}=await sb.from(table).select('*').order(table==='entre_profiles'||table==='entre_members'?'user_id':'id').range(page*500,page*500+499);if(error)throw error;all.push(...data);if(data.length<500)return all;if(page>100)throw Error('Too many records')}}
async function refresh(){if(!user||loading)return;loading=true;const token=generation;try{
 const [m,p,r]=await Promise.all([rows('entre_members'),rows('entre_profiles'),rows('entre_records')]);if(token!==generation)return;
 const previous=members.find(x=>x.user_id===user.id)?.space_id,next=m.find(x=>x.user_id===user.id)?.space_id;
 members=m;profiles=p;records=r;verified=true;lastSync=Date.now();$('#connection').textContent='Actualizado · Tu cuenta';$('#notice').innerHTML='';
 if(previous&&previous!==next){close(true);toast('El vínculo cambió. Ahora solo conservas tus registros propios.')}
 if(!p.some(x=>x.user_id===user.id)&&user.user_metadata?.display_name){await rpc('entre_set_name',{p_name:user.user_metadata.display_name.slice(0,35)});profiles.push({user_id:user.id,display_name:user.user_metadata.display_name.slice(0,35)})}
 render();
 }catch(e){if(token!==generation)return;verified=false;members=[];if(modal.open&&!body.querySelector('form'))close(true);profiles=profiles.filter(x=>x.user_id===user.id);$('#connection').textContent='Sin confirmar conexión';$('#notice').innerHTML=`<div class="notice"><p>${esc(errorText(e))} Ocultamos los registros de tu pareja hasta verificar el vínculo.</p>${button('Reintentar','refresh')}</div>`;render();}finally{loading=false}}
async function put(kind,payload,shared=false,existing=null,recordId=crypto.randomUUID()){const result=await rpc('entre_put_record',{p_id:existing?.id||recordId,p_kind:kind,p_payload:payload,p_shared:shared,p_expected_revision:existing?.revision||0});records=records.filter(r=>r.id!==result.id).concat(result);return result}
function routeTo(r){if(!user)return;if(!close())return;route=['hoy','explorar','nosotros','espacio'].includes(r)?r:'hoy';history.replaceState(null,'','#'+route);render();main.focus();window.scrollTo(0,0)}
function render(){if(!user)return;$('#profile').textContent=myName();$('#navigation').innerHTML=[['hoy','Inicio'],['explorar','Actividades'],['nosotros','Nosotros'],['espacio','Mi espacio']].map(([r,t])=>`<a href="#${r}" ${route===r?'class="active" aria-current="page"':''}>${t}</a>`).join('');main.innerHTML=({hoy:home,explorar:activities,nosotros:couple,espacio:personal}[route])();}
const tile=(title,description,action,id='',color='lavender')=>`<button class="card" data-action="${action}" data-id="${esc(id)}"><span class="label">${esc(description)}</span><h3>${esc(title)}</h3><span class="card-bottom"><span>A tu ritmo</span><span aria-hidden="true">↗</span></span></button>`;
function home(){const today=new Date().toDateString(),done=mine().some(r=>r.kind==='checkin'&&new Date(r.created_at).toDateString()===today);return `<span class="eyebrow">UN POCO DE TIEMPO, SIN PRISA</span><h1>Hola, <em>${esc(myName())}.</em></h1><div class="home-dashboard"><section class="daily-card"><span class="eyebrow">PARA EMPEZAR · 2 MIN</span><h2>${done?'Ya te has escuchado hoy.':'¿Cómo llegas hoy?'}</h2><p>Cuenta cómo estás y elige si quieres compartirlo.</p>${button(done?'Volver a escucharme':'Contar cómo estoy','checkin','','')}<span class="daily-orbits" aria-hidden="true"></span></section><div class="grid cloud-catalog">${tile('Preguntas','Conoceros un poco más','questions')}${tile('Agradecer','Un gesto que sí viste','appreciation')}${tile('Acuerdos','Lo que queréis cuidar','agreements')}${tile('Una discusión','Hablar y reparar','repair')}${tile('Deseo','Coincidencias sin presión','desire')}${tile('Planes para dos','Fuera de la pantalla','dates')}</div></div>${!partner()?`<div class="cloud-note"><h3>Dos móviles. Un espacio.</h3><p>Cada persona entra con su correo. Vinculaos cuando ambos queráis.</p>${button('Vincular nuestras cuentas','pair')}</div>`:''}<div class="cloud-toolbar">${button('Un momento para mí','journal')}${button('Mis favoritas','favorites')}${button('Necesito una pausa','pause')}</div><p class="cloud-muted">No puntuamos vuestra relación. Tus reflexiones son privadas; tú eliges qué compartes.</p>`}
function activities(){return `<h1>Actividades</h1><p class="intro">Todo lo que buscáis, a mano.</p><div class="cloud-toolbar">${button('Preguntas','questions')}${button('Planes','dates')}${button('Recorridos','paths')}${button('Buscar','search')}</div><div class="grid cloud-catalog">${MODULES.map(m=>tile(m.title,m.description,'module',m.id)).join('')}</div>`}
function cardRecord(r){const p=r.payload,own=r.owner_id===user.id;const title=p.title||p.action||({checkin:'Cómo llego hoy',appreciation:'Un gesto que importa',agreement:'Nuestra propuesta',note:'Mi reflexión',completion:'Momento completado',date:'Un plan para dos'}[r.kind]||'Un momento');const text=r.kind==='checkin'?[p.mood,p.need,p.text].filter(Boolean).join('\n'):p.text||p.review||'';return `<article class="cloud-card"><span class="badge">${r.kind==='agreement'?esc(agreementState(r)):r.shared?'Compartido con tu pareja':'Solo tu cuenta'}</span><h3>${esc(title)}</h3>${text?`<p>${esc(text)}</p>`:''}${r.kind==='agreement'&&p.date?`<p>Revisar: ${esc(p.date)}</p>`:''}<div class="cloud-date">${esc(displayName(r.owner_id))} · ${fmt(r.created_at)}</div><div class="cloud-actions">${r.kind==='agreement'&&r.shared?button((r.accepted_by||[]).includes(user.id)?'Ya has aceptado':'Aceptar por mi parte','accept',`data-id="${r.id}"`):''}${own&&r.kind==='agreement'?button('Editar / revisar','edit',`data-id="${r.id}"`):''}${own?button('Eliminar','delete',`data-id="${r.id}"`,'ghost'):''}</div></article>`}
function couple(){const list=visible().filter(r=>r.shared&&['checkin','agreement','appreciation'].includes(r.kind)).sort((a,b)=>b.created_at.localeCompare(a.created_at));return `<h1>Nosotros</h1><p class="intro">${partner()?esc(myName())+' y '+esc(displayName(partner().user_id)):'Un vínculo que elegís los dos.'}</p><div class="cloud-toolbar">${button('Nuestro vínculo','pair')}${button('Nueva propuesta','agreement')}${button('Escribir un aprecio','appreciation')}${button('Acuerdos','agreements')}</div><div class="cloud-list">${list.length?list.map(cardRecord).join(''):'<div class="cloud-empty">Aquí aparecerá lo que decidáis compartir.</div>'}</div>`}
function personal(){const list=mine().filter(r=>['note','checkin','agreement','appreciation'].includes(r.kind)).sort((a,b)=>b.created_at.localeCompare(a.created_at));return `<h1>Mi espacio</h1><p class="intro">Contigo también, ${esc(myName())}.</p><div class="cloud-toolbar">${button('Mi diario','journal')}${button('Mi autonomía','module','data-id="autonomia"')}${button('Ajustes','settings')}</div><p class="cloud-note">Las reflexiones y el diario son privados en la app. Cada registro indica si lo compartiste. Al guardarlo se envía a tu cuenta en Supabase.</p><div class="cloud-list">${list.length?list.map(cardRecord).join(''):'<div class="cloud-empty">Lo que decidas guardar aparecerá aquí.</div>'}</div>`}
function recordForm(kind,existing=null){const p=existing?.payload||{},isAgreement=kind==='agreement';if(existing&&existing.owner_id!==user.id)return;const id=existing?.id||crypto.randomUUID();show(isAgreement?'Una propuesta concreta.':kind==='checkin'?'¿Cómo llegas hoy?':kind==='appreciation'?'Un gesto que sí viste.':'Un momento para ti.',`<form id="record-form" class="cloud-form">${kind==='checkin'?`<label>Cómo me siento<select id="mood">${['Con calma','Con ilusión','Con cansancio','Con tensión','Con tristeza','No lo sé'].map(x=>`<option>${x}</option>`).join('')}</select></label>${input('need','Qué me ayudaría','text','','maxlength="100" required')}`:''}${isAgreement?`${input('action','Una acción pequeña y concreta','text',p.action||'','required maxlength="500"')}${input('owner','Quién se propone hacerlo','text',p.owner||myName(),'required maxlength="100"')}${input('date','Cuándo revisarlo (opcional)','date',p.date||'')}${textarea('review','Qué habéis observado (opcional)',p.review||'')}<p class="help">Editar una propuesta reinicia las aceptaciones. Cada persona tendrá que aceptar de nuevo desde su cuenta.</p>`:textarea('text',kind==='appreciation'?'Qué hizo y cómo te ayudó':kind==='checkin'?'Algo más que quieras contar (opcional)':'Tu reflexión',p.text||'')}${kind==='note'?'<p class="help">Solo tú podrás ver esta reflexión desde la app. Se guardará en tu cuenta de Supabase.</p>':privacyChoice()}<button type="submit" class="button">Guardar${kind==='note'?' en privado':''}</button></form>`);if(existing?.shared&&$('#share'))$('#share').checked=true;
 $('#record-form').onsubmit=e=>{e.preventDefault();const shared=$('#share')?.checked||false,payload=isAgreement?{action:$('#action').value.trim(),owner:$('#owner').value.trim(),date:$('#date').value,review:$('#review').value.trim()}:kind==='checkin'?{mood:$('#mood').value,need:$('#need').value.trim(),text:$('#text').value.trim()}:{title:kind==='note'?'Mi diario':'Un gesto que importa',text:$('#text').value.trim()};if(!isAgreement&&kind!=='checkin'&&!payload.text){$('#modal-error').textContent='Escribe algo antes de guardar, o cierra sin guardar.';return}task(async()=>{await saveOnce(id,kind,payload,shared,existing);dirty=false;close(true);render();toast(shared?'Guardado y compartido con tu pareja.':'Guardado en tu cuenta, sin compartir.');refresh()})};}
// Stable UUID per form. After a lost response, read back before retrying: never overwrite a changed revision.
async function saveOnce(id,kind,payload,shared,existing){try{return await put(kind,payload,shared,existing,id)}catch(e){const {data,error}=await sb.from('entre_records').select('*').eq('id',id).maybeSingle();const comparable={...payload};if(kind==='agreement'){delete comparable.status;delete comparable.accepted;delete comparable.accepted_by}if(!error&&data&&!data.deleted_at&&data.owner_id===user.id&&data.kind===kind&&data.shared===shared&&JSON.stringify(stable(data.payload))===JSON.stringify(stable(comparable))){records=records.filter(r=>r.id!==id).concat(data);return data}throw e}}
function stable(x){if(Array.isArray(x))return x.map(stable);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])]));return x}
function pair(){show('Dos cuentas. Un vínculo.',partner()?`<p>Estás vinculado con <strong>${esc(displayName(partner().user_id))}</strong>. Cada persona decide qué comparte.</p><p>Al desvincularos, cada uno conserva sus registros propios. Dejáis de ver los del otro. Las copias ya descargadas no se pueden retirar.</p>${button('Desvincular nuestras cuentas','unlink','','danger')}`:`<p>Uno crea el código y lo comparte fuera de la app. La otra persona entra con su propio correo y pega ese código aquí. ENTRE no envía invitaciones por su cuenta.</p><div class="cloud-actions">${button('Crear código de invitación','invite','','')}${button('Revocar mi código anterior','revoke')}</div><form id="join-form" class="cloud-form cloud-section">${input('invite-code','Tengo un código','text','','required minlength="64" maxlength="64" autocomplete="off" spellcheck="false"')}<label class="check-label"><input required type="checkbox"> Quiero vincular mi cuenta con quien me ha dado este código.</label><button class="button" type="submit">Vincular mi cuenta</button></form><p class="help">El código caduca en 24 horas y solo se puede usar una vez. Si ya creaste tu propio espacio, desvincúlalo antes de usar un código ajeno.</p>${members.length?button('Desvincular mi espacio pendiente','unlink','','ghost'):''}`);if($('#join-form'))$('#join-form').onsubmit=e=>{e.preventDefault();const code=$('#invite-code').value.trim();task(async()=>{await rpc('entre_join',{p_code:code});dirty=false;close(true);await refresh();routeTo('nosotros');toast('Cuentas vinculadas. Nada anterior se comparte automáticamente.')})}}
function invite(){task(async()=>{const data=await rpc('entre_create_invite');show('Vuestra invitación.',`<p>Comparte este código solo con tu pareja. Se podrá unir al aceptarlo desde su cuenta.</p><p class="cloud-code" id="invite-value">${esc(data.code)}</p>${button('Copiar código','copy-invite')}<p class="help">Caduca: ${esc(new Date(data.expires_at).toLocaleString('es-ES'))}. Generar otro invalida el anterior.</p>`);await refresh()})}
async function accept(id){const r=records.find(x=>x.id===id);if(!r||!verified)return;if((r.accepted_by||[]).includes(user.id)){toast('Tu aceptación ya está registrada.');return}show('Aceptar por tu parte.',`<p>${esc(r.payload.action)}</p><p>Solo registras tu propia aceptación. La otra persona decide desde su cuenta.</p>${button('Sí, acepto esta propuesta','confirm-accept',`data-id="${r.id}" data-revision="${r.revision}"`,'')}`)}
function agreements(){show('Nuestros acuerdos.',`<p>Cada aceptación pertenece a una cuenta. No tienes que aceptar una propuesta por verla aquí.</p>${button('Nueva propuesta','agreement','','')}<div class="cloud-list cloud-section">${visible().filter(r=>r.kind==='agreement').map(cardRecord).join('')||'<p>Aún no hay propuestas.</p>'}</div>`)}
function exercise(id){const m=MODULES.find(x=>x.id===id);if(!m)return;if(m.adult&&!adult){adultGate(()=>exercise(id));return}const saveId=crypto.randomUUID();show(esc(m.title),`<span class="label">${esc(m.basis)}</span><p>${esc(m.description)}</p>${m.together?'<p class="cloud-note">Hacedlo solo cuando ambos queráis conversar. Puedes parar o hacer tu reflexión individual sin guardar.</p>':''}<form id="exercise-form" class="cloud-form">${m.steps.map((s,i)=>`<fieldset><legend>${i+1} · ${esc(s.title)}</legend><p>${esc(s.question)}</p>${textarea('answer-'+i,'Mi reflexión (opcional)')}${s.tip?`<p class="help">${esc(s.tip)}</p>`:''}</fieldset>`).join('')}<p class="help">Si guardas, el texto irá a tu cuenta en Supabase. Será privado en la app. No puntúa la relación.</p><label>¿Te ha servido?<select id="helpful"><option>Prefiero no responder</option><option>Me ha ayudado</option><option>Me ha dejado igual</option><option>Me ha incomodado</option></select></label><button class="button" type="submit">Guardar mi reflexión en privado</button>${button('Terminar sin guardar textos','exercise-complete',`data-id="${esc(id)}"`)}${button('Necesito una pausa','pause')}${button('Necesito apoyo individual','safety','','ghost')}</form>`);$('#exercise-form').onsubmit=e=>{e.preventDefault();const text=m.steps.map((s,i)=>s.title+'\n'+$('#answer-'+i).value.trim()).join('\n\n'),helpful=$('#helpful').value;task(async()=>{await saveOnce(saveId,'note',{title:m.title,module:m.id,text,helpful},false,null);dirty=false;close(true);render();toast('Reflexión guardada solo para tu cuenta.')})}}
function paths(){show('Pequeños recorridos.',PATHS.map(p=>`<section class="cloud-card cloud-section"><h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p>${p.modules.map(id=>{const m=MODULES.find(x=>x.id===id),done=mine().some(r=>r.payload.module===id);return `<div class="cloud-actions">${button((done?'✓ ':'')+esc(m.title),'module',`data-id="${id}"`)}</div>`}).join('')}</section>`).join(''))}
function repair(){show('Primero, bajar la intensidad.',`<p>No hace falta resolverlo ahora. Elegid un momento en el que podáis escucharos.</p><div class="cloud-list">${tile('Necesito una pausa','Volver cuando haya disponibilidad','pause')}${tile('Hablar sin atacar','Hechos, emoción y petición','module','conflicto')}${tile('Reparar con hechos','Escuchar y asumir la propia responsabilidad','module','reparar')}</div>${button('Hay miedo, amenazas o violencia','safety','','ghost')}`)}
function safety(){show('Tu bienestar primero.',`<p>Si hay miedo, amenazas, coacción o violencia, este no es el momento para un ejercicio conjunto. No necesitas compartir tus respuestas ni negociar tu seguridad.</p><p>Busca apoyo individual de alguien de confianza o de un profesional. Si existe peligro inmediato, contacta con emergencias de tu zona.</p><p class="help">ENTRE no detecta emergencias ni avisa a nadie. Cerrar esta ventana no borra el historial del navegador.</p>${button('Cerrar','close')}`)}
function pause(){if(dirty&&!close())return;show('Ahora, un poco de espacio.',`<p>Puedes parar. Si os ayuda, acordad fuera de la app cuándo revisar si estáis preparados para hablar. El temporizador no os obliga a retomar.</p><div class="cloud-toolbar">${[5,10,20,30].map(x=>button(x+' min','pause-time',`data-minutes="${x}"`)).join('')}</div><p class="cloud-pause" id="clock" role="timer">20:00</p><div class="cloud-actions">${button('Iniciar','pause-toggle')}${button('Necesito apoyo','safety','','ghost')}</div><p class="help">Solo se muestra en este móvil. No se notifica a tu pareja.</p>`);let seconds=1200,end=null;const update=()=>{const n=end?Math.max(0,Math.ceil((end-Date.now())/1000)):seconds;$('#clock').textContent=Math.floor(n/60)+':'+String(n%60).padStart(2,'0');if(end&&n===0){end=null;seconds=0;$('#clock').textContent='A tu ritmo.'}};const interval=setInterval(update,500);modalCleanup=()=>clearInterval(interval);body.querySelector('[data-action="pause-toggle"]').onclick=e=>{if(end){seconds=Math.max(0,Math.ceil((end-Date.now())/1000));end=null;e.currentTarget.textContent='Continuar'}else{end=Date.now()+seconds*1000;e.currentTarget.textContent='Pausar'}update()};body.querySelectorAll('[data-action="pause-time"]').forEach(b=>b.onclick=()=>{end=null;seconds=Number(b.dataset.minutes)*60;update()})}
function adultGate(next){show('Un espacio opcional · +18',`<p>Puedes omitir cualquier pregunta o parar. El interés no equivale a consentimiento.</p><label class="check-label"><input id="adult" type="checkbox"> Soy mayor de 18 años y quiero abrir este espacio.</label><button id="adult-next" class="button">Continuar</button>`);$('#adult-next').onclick=()=>{if(!$('#adult').checked){$('#modal-error').textContent='Confirma tu elección para continuar.';return}adult=true;next()}}
function questions(favorites=false){show(favorites?'Tus favoritas.':'Una pregunta. Todo el tiempo.',`<p>120 preguntas originales. El historial de preguntas vistas es personal y se sincroniza con tu cuenta.</p><div class="cloud-toolbar"><label>Tema<select id="question-topic"><option value="all">Todos</option>${TOPICS.map(t=>`<option value="${t[0]}">${esc(t[1])}</option>`).join('')}</select></label><label>Profundidad<select id="question-level"><option value="all">Todas</option><option value="1">Cotidiana</option><option value="2">Personal</option><option value="3">Profunda</option></select></label></div><div id="question-area"></div>`);$('#question-topic').value=questionFilter;$('#question-level').value=questionLevel;const draw=()=>{questionFilter=$('#question-topic').value;questionLevel=$('#question-level').value;if(questionFilter==='intimidad'&&!adult){adultGate(()=>questions(favorites));return}const seen=new Set(mine().filter(r=>r.kind==='seen').map(r=>r.payload.value)),fav=new Set(mine().filter(r=>r.kind==='favorite').map(r=>r.payload.value));const list=QUESTIONS.filter(q=>(questionFilter==='all'||q.topic===questionFilter)&&(questionLevel==='all'||q.level===Number(questionLevel))&&(!q.adult||adult)&&(favorites?fav.has(q.id):!seen.has(q.id)));question=list[0]||null;$('#question-area').innerHTML=question?`<p class="question-big">${esc(question.text)}</p><p class="help">Puedes responder en voz alta, escribir una reflexión privada o pasar. No se exige ninguna respuesta.</p><div class="cloud-actions">${button(fav.has(question.id)?'Quitar de favoritas':'Guardar favorita','favorite',`data-id="${esc(question.id)}"`)}${button('Reflexionar en privado','question-note')}${button('Marcar vista y seguir','question-next',`data-id="${esc(question.id)}"`,'')}</div><p class="help">${list.length} ${favorites?'favoritas disponibles':'preguntas sin explorar con este filtro'}.</p>`:`<p class="cloud-empty">${favorites?'No hay favoritas con este filtro.':'Has explorado todas las preguntas de este filtro. Puedes cambiarlo o volver a tus favoritas.'}</p>`;};$('#question-topic').onchange=draw;$('#question-level').onchange=draw;draw()}
function questionNote(){if(!question)return;const q=question,id=crypto.randomUUID();show('Lo que te hace pensar.',`<p class="question-big">${esc(q.text)}</p><form class="cloud-form" id="question-form">${textarea('answer','Tu respuesta privada')}<p class="help">Se guardará en tu cuenta, sin compartir con tu pareja.</p><button class="button" type="submit">Guardar en privado</button></form>`);$('#question-form').onsubmit=e=>{e.preventDefault();const text=$('#answer').value.trim();if(!text)return;task(async()=>{await saveOnce(id,'note',{title:q.text,text,module:'preguntas'},false,null);dirty=false;close(true);render();toast('Respuesta guardada en privado.')})}}
function dates(){show('Fuera de la pantalla.',`<div class="cloud-list">${DATES.map((d,i)=>`<article class="cloud-card"><span class="label">${d.minutes} min · ${esc(d.cost)}</span><h3>${esc(d.title)}</h3><p>${esc(d.text)}</p><p>${esc(d.question)}</p>${button(mine().some(r=>r.kind==='date'&&r.payload.value===i)?'Plan explorado ✓':'Marcar como explorado','date-done',`data-index="${i}"`)}</article>`).join('')}</div>`)}
function search(){show('¿Qué necesitas ahora?',`<input class="cloud-search" id="find" type="search" placeholder="Preguntas, acuerdos, pausa…" aria-label="Buscar actividades"><div id="results" class="cloud-list"></div>`);const items=[['Cómo llego hoy','checkin',''],['Preguntas e intimidad progresiva','questions',''],['Apreciar y agradecer','appreciation',''],['Acuerdos y seguimiento','agreements',''],['Una discusión y reparaciones','repair',''],['Deseo y coincidencias','desire',''],['Pausa con temporizador','pause',''],['Mi diario privado','journal',''],['Planes para dos','dates',''],['Recorridos','paths',''],['Vincular mi pareja','pair',''],['Ajustes, cuenta y copias','settings',''],...MODULES.map(m=>[m.title+' · '+m.description,'module',m.id])];const normalize=x=>x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const draw=()=>{$('#results').innerHTML=items.filter(x=>normalize(x[0]).includes(normalize($('#find').value))).map(([t,a,id])=>button(esc(t),a,`data-id="${esc(id)}"`)).join('')||'<p>No encontramos esa actividad.</p>'};$('#find').oninput=draw;draw();$('#find').focus()}
async function desire(){if(!adult){adultGate(()=>task(desire));return}if(!partner()||!verified){pair();return}const {data,error}=await sb.from('entre_desire_sessions').select('*').is('closed_at',null).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1);if(error)throw error;const session=data[0];if(!session){show('Curiosidad sin obligación.',`<p>Cada persona responde desde su móvil. Solo se mostrarán las opciones afirmativas que coincidan, cuando ambos lo autoricéis.</p><p>No verás los «no», los «quizá» ni las opciones que la otra persona omita. Coincidir no es consentir hacer algo.</p>${button('Iniciar una ronda de 24 horas','desire-start','','')}`);return}
 const result=await rpc('entre_desire_result',{p_session:session.id});if(result.state==='ready'){show('Esto os despierta curiosidad.',`<p>Ambos habéis autorizado ver las coincidencias. Podéis cambiar de opinión sobre cualquier propuesta.</p><div class="cloud-list">${result.matches.length?result.matches.map(i=>`<div class="cloud-card"><h3>${esc(DESIRE_OPTIONS[i])}</h3></div>`).join(''):'<p>No hay coincidencias afirmativas esta vez. No significa nada sobre vuestra relación.</p>'}</div>${button('Cerrar ronda y borrar respuestas','desire-close',`data-id="${session.id}"`)}<p class="help">Cerrar retira el resultado de ambos móviles cuando actualicen. Lo que ya se haya visto no se puede deshacer.</p>`);return}if(result.state==='closed'){show('La ronda ha terminado.',button('Volver al menú','desire'));return}
 show('Tu deseo, a tu ritmo.',`<p>Solo tu cuenta envía estas respuestas. No son visibles para tu pareja. Si autorizáis ambos, solo verá las coincidencias afirmativas.</p><form id="desire-form" class="cloud-form">${DESIRE_OPTIONS.map((t,i)=>`<label>${esc(t)}<select id="desire-${i}"><option value="skip">Prefiero omitirlo</option><option value="yes">Me apetece explorar</option><option value="maybe">Quizá, hablando antes</option><option value="no">Ahora no</option></select></label>`).join('')}<label class="check-label"><input type="checkbox" id="reveal"> Autorizo mostrar únicamente nuestras coincidencias afirmativas cuando mi pareja también lo autorice.</label><button class="button" type="submit">Guardar mis elecciones</button></form><div class="cloud-actions">${button('Consultar coincidencias','desire-result',`data-id="${session.id}"`)}${button('Cerrar ronda y borrar respuestas','desire-close',`data-id="${session.id}"`,'ghost')}</div><p class="help">La ronda caduca en 24 horas. Si ya enviaste respuestas, este formulario no las precarga: guardarlo sustituirá tus elecciones anteriores mientras la ronda siga abierta.</p>`);
 $('#desire-form').onsubmit=e=>{e.preventDefault();const choices=Object.fromEntries(DESIRE_OPTIONS.map((_,i)=>[String(i),$('#desire-'+i).value])),reveal=$('#reveal').checked;task(async()=>{await rpc('entre_submit_desire',{p_session:session.id,p_choices:choices,p_reveal:reveal});dirty=false;show('Tus elecciones están guardadas.',`<p>${reveal?'Cuando tu pareja también autorice, podréis consultar las coincidencias.':'No has autorizado mostrar coincidencias. Puedes volver para cambiar esa elección.'}</p>${button('Consultar coincidencias','desire-result',`data-id="${session.id}"`)}${button('Revisar mis elecciones','desire')}${button('Cerrar ronda y borrar','desire-close',`data-id="${session.id}"`,'ghost')}`)})};}
function privacy(){show('Lo íntimo merece claridad.',`<h3>Cuenta personal</h3><p>Correo electrónico, identidad de acceso y los registros que decidas guardar se alojan en Supabase. Vercel sirve la web. Ambos proveedores pueden procesar datos técnicos necesarios para prestar el servicio.</p><h3>Qué compartes</h3><p>Diario, reflexiones, favoritas y progreso son privados dentro de la app. Check-ins, aprecios y acuerdos solo se comparten si marcas esa opción. Cada pareja tiene un vínculo de dos cuentas. No hay publicidad, seguimiento comercial ni IA conectada.</p><h3>Protección y límites</h3><p>La conexión utiliza HTTPS y la base comprueba permisos por usuario. No es cifrado de extremo a extremo: los administradores autorizados del proyecto pueden acceder a los datos. La sesión de acceso se conserva en este navegador; cierra sesión en dispositivos compartidos. No guardamos una copia local de los registros de la nube entre sesiones.</p><h3>Desvincular y borrar</h3><p>Puedes desvincularte, borrar tus registros o solicitar el borrado de tu cuenta desde Ajustes. Borrar no elimina copias descargadas ni lo que otra persona haya visto. Las respuestas de deseo se borran al cerrar la ronda; la caducidad por sí sola no garantiza su borrado físico.</p><h3>Sin conexión</h3><p>No afirmamos que algo esté guardado hasta recibir confirmación. Los borradores de esta versión viven en la pestaña y se pierden si la cierras. Las copias de seguridad descargables pueden cifrarse con una contraseña propia.</p><h3>Versión local anterior</h3><p>Sus datos siguen en este navegador y no se suben automáticamente. Su contraseña es independiente de la cuenta online.</p><p class="help">Antes de una publicación comercial o en Google Play, el titular debe completar una política pública con su identidad, contacto, plazos de conservación y ejercicio de derechos. Esta pantalla explica el funcionamiento técnico actual.</p>`)}
function about(){show('Cerca, sin dejar de ser tú.',`<p>ENTRE reúne preguntas, escucha, acuerdos, autonomía y deseo en momentos pequeños.</p><p>Contenido educativo original inspirado en Gottman, Sue Johnson, Esther Perel, Imago, Arthur Aron, Terrence Real y Silvia Congost. No está avalado por ellos ni ha sido validado clínicamente. No es terapia, diagnóstico ni una medida de vuestro amor.</p><p>Las actividades se pueden explorar sin guardar textos. En ejercicios conjuntos, ambos deben poder parar.</p>${button('Privacidad','privacy')}`)}
function settings(){show('Tu espacio, tus decisiones.',`<p>${esc(myName())} · ${esc(user.email)}</p><div class="cloud-list"><section class="cloud-card"><h3>Tu cuenta personal</h3><form class="cloud-form" id="name-form">${input('new-name','Nombre o apodo','text',myName(),'required maxlength="35"')}<button type="submit" class="button secondary">Guardar nombre</button></form><div class="cloud-actions">${button('Cambiar contraseña','change-password')}${button('Cerrar sesión','logout')}</div></section><section class="cloud-card"><h3>Vuestro vínculo</h3><p>${partner()?'Compartes espacio con '+esc(displayName(partner().user_id)):'Aún no hay dos cuentas vinculadas.'}</p>${button('Gestionar vínculo','pair')}</section><section class="cloud-card"><h3>Tu copia y tus datos anteriores</h3><p>Exporta tus propios registros con una contraseña. La importación exige revisar quién escribió cada dato y empieza siempre en privado.</p><div class="cloud-actions">${button('Descargar copia cifrada','backup')}${button('Importar una copia','import')}</div><p><a href="local.html">Abrir la versión local anterior</a></p></section><section class="cloud-card"><h3>Apariencia</h3>${button(theme==='dark'?'Cambiar a modo claro':'Cambiar a modo oscuro','theme')}${button('Reducir movimiento','motion')}${button('Privacidad','privacy')}</section><section class="cloud-card"><h3>Borrar</h3><p>Borrar mis datos también desvincula el espacio. Tu pareja conserva sus propios registros. Las copias descargadas no se borran.</p>${button('Borrar solo mis datos','delete-data','','danger')}<div class="cloud-delete">${button('Eliminar mi cuenta y mis datos','delete-account','','danger')}</div><p class="help">El borrado completo requiere el endpoint de servidor incluido en esta entrega y su configuración en Vercel. Si falta, la app te lo indicará sin afirmar que la cuenta se ha borrado.</p></section></div>`);$('#name-form').onsubmit=e=>{e.preventDefault();const name=$('#new-name').value.trim();task(async()=>{await rpc('entre_set_name',{p_name:name});dirty=false;await refresh();close(true);toast('Nombre actualizado.')})}}
function backup(){show('Una copia solo tuya.',`<p>Incluye únicamente tus registros, también los que hayas compartido. El archivo se cifrará con una contraseña que tú elijas. No es tu contraseña de acceso.</p><form id="backup-form" class="cloud-form">${input('backup-password','Contraseña para esta copia','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}${input('backup-repeat','Repite la contraseña','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}<button class="button" type="submit">Descargar copia cifrada</button></form>`);$('#backup-form').onsubmit=e=>{e.preventDefault();const password=$('#backup-password').value;if(password!==$('#backup-repeat').value){$('#modal-error').textContent='Las contraseñas no coinciden.';return}task(async()=>{await refresh();if(!verified)throw Error('network');const data={format:'entre.cloud.backup.v1',owner:user.id,exported_at:new Date().toISOString(),records:mine().map(r=>({id:r.id,kind:r.kind,payload:r.payload,created_at:r.created_at}))};const {vault}=await makeVault(password,data);download(JSON.stringify(vault),'ENTRE-mi-copia-cifrada.json');dirty=false;close(true);toast('Copia descargada. Conserva su contraseña.')})}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importBackup(){show('Traer solo lo que es tuyo.',`<p>No se subirá nada hasta que revises los registros y confirmes. Los datos importados serán privados; los acuerdos volverán a ser propuestas sin aceptaciones.</p><form id="import-form" class="cloud-form"><label>Copia de ENTRE<input id="backup-file" type="file" accept=".json,application/json" required></label>${input('import-password','Contraseña de la copia (si está cifrada)','password','','autocomplete="off"')}<button type="submit" class="button">Abrir y revisar</button></form>`);$('#import-form').onsubmit=e=>{e.preventDefault();const file=$('#backup-file').files[0],password=$('#import-password').value;task(async()=>{if(file.size>15000000)throw {userMessage:'La copia es demasiado grande para esta importación (máximo 15 MB).'};let data=JSON.parse(await file.text());if(data.format!=='entre.cloud.backup.v1'&&data.version!==2){const opened=await unlockVault(checkVault(data),password);data=opened.data}if(data.format==='entre.cloud.backup.v1'){if(!Array.isArray(data.records)||data.records.length>15000)throw Error('invalid backup');previewImport(data.records.map(r=>({...privateImportPayload(r),id:crypto.randomUUID()})));return}const local=validate(data);show('¿Cuáles son tus registros?',`<p>Los nombres de la versión local eran etiquetas, no identidades verificadas. Elige la tuya. No incluiremos acuerdos o actividades antiguos sin una autoría individual clara.</p><div class="cloud-actions">${local.settings.names.map((n,i)=>button(esc(n),'import-person',`data-person="${i}"`)).join('')}</div>`);body.querySelectorAll('[data-action="import-person"]').forEach(b=>b.onclick=()=>{const person=Number(b.dataset.person);const list=[...local.notes.filter(r=>r.person===person).map(r=>({kind:'note',payload:{title:r.title,text:r.text,module:r.module}})),...local.checkins.filter(r=>r.person===person).map(r=>({kind:'checkin',payload:{mood:r.mood,need:r.need,text:r.text}})),...local.gratitudes.filter(r=>r.person===person).map(r=>({kind:'appreciation',payload:{text:r.text}}))].map(r=>({...r,id:crypto.randomUUID()}));previewImport(list)})})}}
function previewImport(list){if(!list.length){show('No hay registros que importar.','<p>Esta selección no contiene textos propios.</p>');return}show('Revisa antes de subir.',`<p>${list.length} registros. Se añadirán a tu cuenta en privado. Desmarca los que no sean tuyos o no quieras subir. Importar otra vez el mismo archivo puede duplicarlos.</p><form id="confirm-import" class="cloud-form"><div style="max-height:45vh;overflow:auto">${list.map((r,i)=>`<label class="check-label"><input type="checkbox" name="record" value="${i}"><span>${esc(r.payload.title||r.payload.action||r.kind)}<small style="display:block;white-space:pre-wrap">${esc(r.payload.text||r.payload.review||r.payload.value||[r.payload.mood,r.payload.need].filter(Boolean).join(' · '))}</small></span></label>`).join('')}</div><label class="check-label"><input type="checkbox" id="own-confirm" required> Confirmo que los registros seleccionados son míos y quiero subirlos a mi cuenta.</label><p id="import-progress" role="status"></p><button class="button" type="submit">Importar selección en privado</button></form>`);const completed=new Set();$('#confirm-import').onsubmit=e=>{e.preventDefault();const selected=[...body.querySelectorAll('[name=record]:checked')].map(n=>Number(n.value));if(!selected.length){$('#modal-error').textContent='Selecciona al menos un registro.';return}task(async()=>{for(const i of selected){if(completed.has(i))continue;const r=list[i];await saveOnce(r.id,r.kind,r.payload,false,null);completed.add(i);$('#import-progress').textContent=completed.size+' registros confirmados. Si se interrumpe, puedes volver a pulsar sin duplicar los ya confirmados.'}dirty=false;close(true);render();toast('Registros importados en privado.')})}}
function changePassword(){show('Cambiar tu contraseña.',`<form id="change-password-form" class="cloud-form">${input('current-password','Contraseña actual','password','','required autocomplete="current-password"')}${input('next-password','Nueva contraseña','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}${input('next-repeat','Repite la nueva contraseña','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}<button class="button" type="submit">Guardar contraseña</button></form>`);$('#change-password-form').onsubmit=e=>{e.preventDefault();const current=$('#current-password').value,next=$('#next-password').value;if(next!==$('#next-repeat').value){$('#modal-error').textContent='Las contraseñas no coinciden.';return}task(async()=>{const {error}=await sb.auth.signInWithPassword({email:user.email,password:current});if(error)throw error;const result=await sb.auth.updateUser({password:next});if(result.error)throw result.error;dirty=false;close(true);toast('Contraseña actualizada.')})}}
function deleteData(account=false){show(account?'Eliminar tu cuenta.':'Borrar tus datos.',`<p>${account?'Se eliminarán tu identidad de acceso y tus registros.':'Se eliminarán tus registros de la nube y tu nombre. Tu cuenta de acceso seguirá existiendo.'} Se deshará el vínculo y tu pareja conservará sus propios registros. Esto no borra copias descargadas ni datos de la versión local.</p><form id="delete-form" class="cloud-form">${input('delete-password','Confirma tu contraseña','password','','required autocomplete="current-password"')}${input('delete-confirm','Escribe BORRAR','text','','required pattern="BORRAR" autocomplete="off"')}<button class="button danger" type="submit">${account?'Eliminar mi cuenta definitivamente':'Borrar mis datos'}</button></form>`);$('#delete-form').onsubmit=e=>{e.preventDefault();const password=$('#delete-password').value;task(async()=>{const {data,error}=await sb.auth.signInWithPassword({email:user.email,password});if(error)throw error;if(account){const response=await fetch('/api/delete-account',{method:'POST',headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(25000)});if(!response.ok){let result={};try{result=await response.json()}catch{}throw {userMessage:result.error||'No se pudo confirmar el borrado de la cuenta. Tus datos no se darán por eliminados. Inténtalo de nuevo.'}}}else {await rpc('entre_delete_my_data');const cleared=await sb.auth.updateUser({data:{display_name:null}});if(cleared.error)throw {userMessage:'Los registros se han borrado, pero no se pudo retirar el nombre del perfil de acceso. Vuelve a intentarlo.'}}dirty=false;close(true);await logout();toast(account?'Tu cuenta ha sido eliminada.':'Tus datos se han borrado. La cuenta de acceso sigue existiendo.')})}}
async function logout(){if(!close())return;generation++;if(channel){sb.removeChannel(channel);channel=null}user=null;records=[];members=[];profiles=[];verified=false;question=null;adult=false;main.innerHTML='';body.innerHTML='';$('#toast').textContent='';$('#notice').innerHTML='';$('#profile').textContent='Mi cuenta';const {error}=await sb.auth.signOut({scope:'local'});login();if(error)$('#auth-error').textContent='Se ha ocultado el espacio, pero no se pudo confirmar el cierre de la sesión. Inténtalo de nuevo antes de dejar este dispositivo.'}
const actions={
 welcome:b=>welcome(Number(b.dataset.step)),login:()=>login(),register:()=>login('register'),recover:()=>login('recover'),privacy,about,close:()=>close(),
 resend:()=>{const email=$('#email')?.value.trim();if(!email){$('#auth-error').textContent='Escribe primero tu correo.';return}task(async()=>{const {error}=await sb.auth.resend({type:'signup',email,options:{emailRedirectTo:APP_URL}});if(error)throw error;toast('Si procede, recibirás otro enlace de confirmación.')})},
 checkin:()=>recordForm('checkin'),journal:()=>recordForm('note'),appreciation:()=>recordForm('appreciation'),agreement:()=>recordForm('agreement'),agreements,edit:b=>recordForm('agreement',records.find(r=>r.id===b.dataset.id)),accept:b=>accept(b.dataset.id),
 'confirm-accept':b=>task(async()=>{const r=await rpc('entre_accept_agreement',{p_id:b.dataset.id,p_expected_revision:Number(b.dataset.revision)});records=records.filter(x=>x.id!==r.id).concat(r);close(true);render();toast('Tu aceptación está registrada.');refresh()}),
 delete:b=>{const r=records.find(r=>r.id===b.dataset.id);if(!r||r.owner_id!==user.id)return;show('Eliminar este registro.',`<p>Se retirará de tu cuenta y, si estaba compartido, del acceso de tu pareja. Las copias descargadas no se borran.</p>${button('Eliminar','confirm-delete',`data-id="${r.id}" data-revision="${r.revision}"`,'danger')}`)},
 'confirm-delete':b=>task(async()=>{await rpc('entre_delete_record',{p_id:b.dataset.id,p_expected_revision:Number(b.dataset.revision)});records=records.filter(r=>r.id!==b.dataset.id);close(true);render();toast('Registro eliminado.')}),
 pair,invite,revoke:()=>task(async()=>{await rpc('entre_revoke_invite');toast('Código revocado.')}),
 unlink:()=>{show('Desvincular nuestras cuentas.',`<p>Ambos conserváis solo vuestros propios registros. Se cerrarán las rondas de deseo. No se eliminan copias que hayáis descargado.</p>${button('Sí, desvincular','confirm-unlink','','danger')}`)},
 'confirm-unlink':()=>task(async()=>{await rpc('entre_leave_space');records=mine().map(r=>({...r,shared:false,space_id:null,accepted_by:[]}));members=[];close(true);await refresh();toast('Cuentas desvinculadas.')}),
 module:b=>exercise(b.dataset.id),repair,safety,pause,paths,questions:()=>questions(),favorites:()=>questions(true),dates,search,
 'exercise-complete':b=>{if(!close())return;task(async()=>{await put('completion',{module:b.dataset.id},false);render();toast('Momento completado. No se han guardado textos.')})},
 'question-note':questionNote,
 'question-next':b=>task(async()=>{if(!mine().some(r=>r.kind==='seen'&&r.payload.value===b.dataset.id))await put('seen',{value:b.dataset.id},false);questions()}),
 favorite:b=>task(async()=>{const old=mine().filter(r=>r.kind==='favorite'&&r.payload.value===b.dataset.id);if(old.length){for(const r of old)await rpc('entre_delete_record',{p_id:r.id,p_expected_revision:r.revision});records=records.filter(r=>!old.some(x=>x.id===r.id))}else await put('favorite',{value:b.dataset.id},false);b.textContent=old.length?'Guardar favorita':'Quitar de favoritas';toast(old.length?'Favorita retirada.':'Favorita guardada en tu cuenta.')}),
 'date-done':b=>task(async()=>{const value=Number(b.dataset.index);if(!mine().some(r=>r.kind==='date'&&r.payload.value===value))await put('date',{value,title:DATES[value].title},false);b.textContent='Plan explorado ✓'}),
 desire:()=>task(desire),'desire-start':()=>task(async()=>{await rpc('entre_start_desire');await desire()}),
 'desire-result':b=>task(async()=>{const r=await rpc('entre_desire_result',{p_session:b.dataset.id});if(r.state==='ready')await desire();else if(r.state==='closed')show('Esta ronda ha terminado.',button('Volver','desire'));else toast('Todavía faltan respuestas o autorización. Podéis hacerlo sin prisa.')}),
 'desire-close':b=>{show('Cerrar la ronda.',`<p>Se borrarán las elecciones de ambos y se retirarán las coincidencias.</p>${button('Cerrar y borrar','confirm-desire-close',`data-id="${b.dataset.id}"`,'danger')}`)},
 'confirm-desire-close':b=>task(async()=>{await rpc('entre_close_desire',{p_session:b.dataset.id});close(true);toast('Ronda cerrada y respuestas borradas.')}),
 settings,backup,import:importBackup,'change-password':changePassword,'delete-data':()=>deleteData(false),'delete-account':()=>deleteData(true),logout:()=>task(logout),
 theme:()=>{theme=theme==='dark'?'light':'dark';document.body.dataset.theme=theme;try{localStorage.setItem('entre.cloud.theme',theme)}catch{}settings()},motion:()=>{document.body.classList.toggle('reduce-motion');toast('Preferencia de movimiento cambiada para esta sesión.')},
 refresh:()=>refresh(),'copy-invite':()=>task(async()=>{try{await navigator.clipboard.writeText($('#invite-value').textContent);toast('Código copiado.')}catch{toast('Mantén pulsado el código para seleccionarlo y copiarlo.')}})
};
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a&&user){e.preventDefault();routeTo(a.hash.slice(1));return}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const fn=actions[b.dataset.action];if(!fn)return;
 const leaves=['pair','settings','module','repair','safety','questions','favorites','dates','search','journal','checkin','appreciation','agreement','desire','paths'];if(dirty&&leaves.includes(b.dataset.action)&&!close())return;
 try{const result=fn(b);if(result?.catch)result.catch(e=>toast(errorText(e)))}catch(e){toast(errorText(e))}});
window.addEventListener('hashchange',()=>{if(user&&!recovery&&/^#(hoy|explorar|nosotros|espacio)$/.test(location.hash))routeTo(location.hash.slice(1))});
window.addEventListener('online',()=>refresh());window.addEventListener('offline',()=>{verified=false;members=[];if(modal.open&&!body.querySelector('form'))close(true);render();$('#connection').textContent='Sin conexión';$('#notice').innerHTML='<div class="notice"><p>Sin conexión. No guardamos nuevos cambios hasta poder confirmarlos. No cierres los formularios con textos pendientes.</p></div>'});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&user)refresh()});
setInterval(()=>{if(user&&!document.hidden&&!busy)refresh()},15000);
sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;user=session?.user;setTimeout(newPassword,0)}else if(event==='SIGNED_OUT'&&user){generation++;user=null;records=[];members=[];profiles=[];verified=false;close(true);main.innerHTML='';login()}});
async function start(){try{const {data,error}=await sb.auth.getSession();if(error)throw error;if(recovery)return;if(data.session){const checked=await sb.auth.getUser();if(checked.error)throw checked.error;await enter(checked.data.user)}else welcome();started=true;}catch(e){login();$('#auth-error').textContent=errorText(e)}}
start();
