export const TOPICS=[
['cotidiano','Lo pequeño','Conoceros sin prisa',1,[
'¿Qué parte pequeña de tu día te gustaría que yo entendiera mejor?',
'¿Qué momento del día te gustaría tener menos ocupado?',
'¿Qué cosa sencilla te ha hecho sonreír esta semana?',
'¿Qué rutina nuestra te hace sentir a gusto?',
'¿Qué música encaja con el momento que estás viviendo?',
'¿Qué comida te trae un recuerdo bonito?',
'¿Qué te ayuda a desconectar después de un día largo?',
'¿En qué rincón te resulta más fácil descansar?',
'¿Qué pequeño cambio haría tu mañana más agradable?',
'¿Qué te apetecería hacer juntos sin necesidad de organizar mucho?']],
['recuerdos','Nuestra historia','Volver a mirar lo vivido',1,[
'¿Qué detalle recuerdas de una de nuestras primeras conversaciones?',
'¿Qué momento inesperado de nuestra historia te hace sonreír?',
'¿Qué lugar asocias con una etapa bonita de nosotros?',
'¿Qué plan sencillo terminó siendo especial?',
'¿Qué costumbre nuestra nació casi sin darnos cuenta?',
'¿Qué has descubierto de mí con el paso del tiempo?',
'¿Qué canción te lleva a un momento compartido?',
'¿Qué recuerdo cotidiano te gustaría conservar?',
'¿Qué dificultad atravesada te enseñó algo sobre ti?',
'¿Qué versión de nosotros recuerdas con ternura?']],
['juego','Un poco de juego','Curiosidad y ligereza',1,[
'Si tuviéramos una tarde sin obligaciones, ¿qué elegirías hacer?',
'¿Qué habilidad absurda te gustaría dominar?',
'¿Qué aventura pequeña podríamos vivir cerca de casa?',
'¿Qué actividad te gustaría enseñarme por pura diversión?',
'¿Qué película te gustaría que viéramos sin mirar el móvil?',
'¿Qué harías en una cita con un presupuesto de diez euros?',
'Si pudiéramos probar un oficio durante un día, ¿cuál elegirías?',
'¿Qué juego de tu infancia te gustaría recuperar?',
'¿Qué cosa te gustaría hacer mal sin que importara?',
'¿Qué nombre le pondrías a nuestra próxima excursión?']],
['mundo','Tu mundo ahora','Actualizar lo que sabemos',2,[
'¿Qué ocupa más espacio en tu cabeza últimamente?',
'¿Qué responsabilidad te está pesando más de lo que parece?',
'¿Qué has aprendido sobre ti este mes?',
'¿Qué proyecto te ilusiona aunque aún no sepas cómo empezarlo?',
'¿Qué conversación reciente te ha hecho pensar?',
'¿Qué parte de tu vida sientes que está cambiando?',
'¿Qué decisión te gustaría tomar con más calma?',
'¿Qué te gustaría que te preguntara más a menudo?',
'¿Qué logro pequeño te gustaría celebrar?',
'¿Qué cosa estás intentando hacer con menos exigencia?']],
['cuidado','Sentir compañía','Pedir y recibir apoyo',2,[
'¿Cómo te gustaría que te acompañara cuando tienes un día difícil?',
'¿Cómo puedo saber si prefieres escucha o ayuda práctica?',
'¿Qué gesto te hace sentir que tengo presente lo que te importa?',
'¿Qué te ayuda cuando no encuentras palabras para explicar cómo estás?',
'¿Qué diferencia hay para ti entre estar juntos y sentir compañía?',
'¿Qué petición pequeña te gustaría hacerme esta semana?',
'¿Cómo podemos decirnos que no tenemos energía sin que suene a rechazo?',
'¿Qué cuidado te resulta fácil ofrecer y cuál recibir?',
'¿Qué te ayuda a recuperar calma después de un desencuentro?',
'¿Qué te gustaría que recordara cuando estás bajo presión?']],
['futuro','Lo que imaginamos','Deseos sin exigencias',2,[
'¿Cómo sería para ti un fin de semana realmente reparador?',
'¿Qué experiencia te gustaría que compartiéramos este año?',
'¿Qué tradición propia te gustaría inventar?',
'¿Qué significa para ti tener una vida tranquila?',
'¿Qué te gustaría que tuviera más espacio en nuestro día a día?',
'¿Qué proyecto individual te gustaría que yo acompañara?',
'¿Qué te gustaría aprender juntos?',
'¿Qué hábito te gustaría dejar atrás sin tener que hacerlo perfecto?',
'¿Qué conversación sobre el futuro preferirías tener despacio?',
'¿Qué pequeña decisión de hoy podría acercarte a una vida que te guste?']],
['equipo','Hacer equipo','Lo visible y lo invisible',2,[
'¿Qué tarea implica más organización de la que parece?',
'¿Qué responsabilidad te gustaría dejar de tener que recordar?',
'¿Qué significa para ti un reparto justo cuando uno tiene menos energía?',
'¿Qué tarea podrías asumir desde la planificación hasta el final?',
'¿Cómo podemos revisar un acuerdo sin convertirlo en un reproche?',
'¿Qué decisión cotidiana te gustaría que tomáramos de otra manera?',
'¿Qué parte del cuidado de nuestra casa no solemos reconocer?',
'¿Cómo te gustaría pedir ayuda antes de sentirte desbordado?',
'¿Qué acuerdo necesita actualizarse porque nuestra vida ha cambiado?',
'¿Qué podría hacer cada uno para que descansar fuera más fácil?']],
['autonomia','Seguir siendo tú','Espacio propio y límites',2,[
'¿Qué actividad propia te gustaría recuperar?',
'¿Qué tiempo a solas te sienta bien?',
'¿Qué amistad te gustaría cuidar más?',
'¿Cómo te gustaría expresar que hoy prefieres hacer otro plan?',
'¿Qué parte de tu identidad quieres seguir explorando?',
'¿Qué significa para ti acompañar sin decidir por el otro?',
'¿Qué necesitas para poder cambiar de opinión con libertad?',
'¿Qué límite cotidiano te gustaría explicar con más claridad?',
'¿Qué proyecto te apetece hacer por ti mismo?',
'¿Cómo podemos respetar ritmos diferentes sin alejarnos?']],
['profundo','Un poco más dentro','Solo si os apetece',3,[
'¿Qué te cuesta pedirme por miedo a cómo pueda reaccionar?',
'¿Qué te gustaría que comprendiera mejor sobre tu manera de protegerte?',
'¿Cuándo te resulta difícil sentirte escuchado?',
'¿Qué parte de ti te gustaría poder mostrar con menos vergüenza?',
'¿Qué situación te hace necesitar más tranquilidad de la habitual?',
'¿Qué te gustaría poder decir sin tener una solución preparada?',
'¿Qué diferencia hay para ti entre discutir y sentirte atacado?',
'¿Qué te ayuda a confiar en que un desacuerdo no tiene que romper el vínculo?',
'¿Qué necesitas que respete cuando no quieres hablar todavía?',
'¿Qué conversación podríamos preparar para un momento de mayor calma?']],
['aprecio','Lo que sí vemos','Reconocer lo que ayuda',1,[
'¿Qué gesto reciente mío te hizo el día más fácil?',
'¿Qué cualidad mía has visto de otra manera últimamente?',
'¿Qué esfuerzo pequeño te gustaría que yo reconociera?',
'¿Qué te gusta de cómo compartimos los momentos tranquilos?',
'¿Qué has admirado de cómo afronté algo recientemente?',
'¿Qué detalle te hace sentir que formamos un equipo?',
'¿Qué acción de esta semana te gustaría agradecer?',
'¿Qué te gustaría que repitiéramos porque te hizo bien?',
'¿Qué forma de cariño valoras aunque no sea llamativa?',
'¿Qué te gusta de quién eres cuando te sientes a gusto conmigo?']],
['intimidad','Nuestra intimidad','Hablar sin expectativas',3,[
'¿Qué condiciones te ayudan a sentirte cómodo al hablar de intimidad?',
'¿Qué diferencia hay para ti entre cariño y deseo?',
'¿Qué te permite sentirte libre para decir sí, no o todavía no?',
'¿Qué tipo de cercanía disfrutas sin esperar que lleve a algo más?',
'¿Qué te hace sentir atractivo al margen de la mirada de otras personas?',
'¿Qué te gustaría que supiéramos sobre nuestros ritmos diferentes?',
'¿Qué lugar ocupan el descanso y el espacio propio en tu deseo?',
'¿Qué forma de juego o novedad te despierta curiosidad?',
'¿Qué te gustaría poder pedir sin sentir presión por corresponder?',
'¿Qué te ayudaría a conversar sobre intimidad con más naturalidad?']],
['reparacion','Volver a encontrarnos','Responsabilidad y cuidado',2,[
'¿Qué frase te ayuda a reconocer que quiero bajar la tensión?',
'¿Cómo podemos pedir una pausa y acordar cuándo comprobar si podemos seguir?',
'¿Qué te ayuda a sentir que una disculpa es concreta?',
'¿Qué necesitas antes de buscar una solución después de discutir?',
'¿Cómo podemos hablar de lo ocurrido sin atribuir intenciones?',
'¿Qué señal te permite notar que te estás saturando?',
'¿Qué acción pequeña podría reparar un descuido cotidiano?',
'¿Cómo podemos expresar que aún necesitamos tiempo?',
'¿Qué acuerdo de conversación nos gustaría practicar?',
'¿Qué parte de una discusión está en tu mano hacer de otra manera?']]
];
export const QUESTIONS=TOPICS.flatMap(([topic,title,subtitle,level,qs])=>qs.map((text,i)=>({id:`${topic}-${i+1}`,topic,level,text,adult:topic==='intimidad'})));
export const MODULES=[
{id:'mapa',icon:'sun',title:'Cómo llego hoy',description:'Poner en palabras tu día y lo que necesitas.',category:'Conectar',minutes:2,color:'coral',basis:'Mapas del amor · Gottman',steps:[{title:'Lo que traigo conmigo',question:'¿Qué ocupa más espacio en tu cabeza hoy?',placeholder:'Hoy me está rondando…'},{title:'Una necesidad concreta',question:'¿Qué te ayudaría ahora: escucha, ayuda, cariño o espacio?',placeholder:'Hoy me ayudaría…'},{title:'Algo que sí puedo pedir',question:'¿Cómo podrías expresarlo de una forma pequeña y concreta?',placeholder:'¿Te vendría bien…?'}]},
{id:'apego',icon:'circles',title:'Lo que hay debajo',description:'Escuchar la emoción detrás de la reacción.',category:'Conectar',minutes:5,color:'lavender',basis:'Seguridad emocional · Sue Johnson',steps:[{title:'Un momento concreto',question:'Cuando pasó ____, lo que pensé fue ____.',placeholder:'Describe tu experiencia, sin adivinar intenciones.'},{title:'Debajo de la reacción',question:'Mostré ____, pero por dentro sentía ____.',placeholder:'Quizá tristeza, miedo, frustración, soledad…'},{title:'Lo que habría ayudado',question:'En aquel momento me habría ayudado ____.',placeholder:'Una petición que la otra persona pueda comprender.'}]},
{id:'conflicto',icon:'pause',title:'Bajar la intensidad',description:'Convertir una queja en una petición clara.',category:'Reparar',minutes:4,color:'sand',basis:'Comunicación y antídotos · Gottman',steps:[{title:'Los hechos, sin etiquetas',question:'¿Qué ocurrió, de forma concreta?',placeholder:'Por ejemplo: hoy he cocinado y recogido.',tip:'Evita «siempre», «nunca» o descalificar a la persona.'},{title:'Cómo te afectó',question:'¿Qué sentiste y qué necesitabas?',placeholder:'Me sentí cansado. Necesitaba ayuda.',tip:'Una emoción no justifica insultar ni amenazar.'},{title:'Una petición posible',question:'¿Qué acción concreta te gustaría pedir?',placeholder:'¿Puedes encargarte de los platos hoy?',tip:'Una petición admite un no o una alternativa.'}]},
{id:'reparar',icon:'bridge',title:'Volver con hechos',description:'Escuchar, responsabilizarse y dar un paso.',category:'Reparar',minutes:8,color:'coral',basis:'Reparación · Gottman e Imago',together:true,steps:[{title:'Primero, disponibilidad',question:'¿Os sentís preparados para escuchar sin descalificar?',placeholder:'Podéis anotar cuándo os vendría mejor.',tip:'Cualquiera puede parar. Si hay miedo o coacción, busca apoyo individual.'},{title:'Reflejar antes de responder',question:'«Lo que entiendo que te dolió fue ____. ¿Lo he entendido?»',placeholder:'Una persona habla y la otra comprueba lo que entendió.',tip:'Intercambiad turnos. Validar es comprender una perspectiva, no estar de acuerdo en todo.'},{title:'Mi responsabilidad',question:'«Lo que sí hice fue ____. Entiendo que pudo afectarte en ____.»',placeholder:'Reconoce un comportamiento concreto, sin añadir un «pero».',tip:'La responsabilidad no tiene por qué ser igual para ambos.'},{title:'Un cambio observable',question:'«La próxima vez haré ____. Podemos revisarlo el día ____.»',placeholder:'Una acción posible y una ocasión para revisarla.',tip:'Aceptar una disculpa no obliga a perdonar ni a continuar una relación.'}]},
{id:'autonomia',icon:'leaf',title:'Yo también importo',description:'Cuidar tus límites y tu vida propia.',category:'Cuidarme',minutes:4,color:'sage',basis:'Autonomía y autoestima · Silvia Congost',solo:true,steps:[{title:'Mi espacio propio',question:'¿Qué amistad, actividad o proyecto te gustaría cuidar más?',placeholder:'Me gustaría recuperar…'},{title:'Un límite que importa',question:'¿Qué necesitas poder elegir o rechazar con libertad?',placeholder:'Me gustaría poder decir…',tip:'Necesitar apoyo es compatible con tener autonomía.'},{title:'Un primer paso',question:'¿Qué acción está en tu mano para cuidarte esta semana?',placeholder:'Un paso pequeño que dependa de ti.'}]},
{id:'equipo',icon:'balance',title:'Hacer equipo',description:'Repartir también lo que no siempre se ve.',category:'Conectar',minutes:5,color:'sage',basis:'Responsabilidad y poder · Terrence Real',steps:[{title:'Lo que pasa desapercibido',question:'Piensa en una tarea: ¿quién la detecta, organiza y ejecuta?',placeholder:'La tarea es… Detecta… Organiza… Ejecuta…'},{title:'Hablar de justicia',question:'¿Qué reparto sería más llevadero teniendo en cuenta vuestra energía y tiempo?',placeholder:'Nos ayudaría ajustar…',tip:'Un reparto justo no tiene por qué ser idéntico.'},{title:'Hacerse cargo',question:'¿Qué responsabilidad puedes asumir completa, sin esperar instrucciones?',placeholder:'Me encargo de… desde… hasta…'}]},
{id:'deseo',icon:'spark',title:'Curiosidad y espacio',description:'Explorar el deseo sin convertirlo en obligación.',category:'Intimidad',minutes:6,color:'lavender',basis:'Deseo y autonomía · Esther Perel',adult:true,steps:[{title:'Las condiciones',question:'Me resulta más fácil conectar con el deseo cuando ____. Me cuesta cuando ____.',placeholder:'Puedes pensar en descanso, juego, espacio propio…'},{title:'Otra mirada',question:'¿En qué situación viste a tu pareja haciendo algo que admiras o te atrae?',placeholder:'Recuerdo cuando…'},{title:'Una posibilidad, no una obligación',question:'¿Qué te despierta curiosidad y qué límites quieres respetar?',placeholder:'Me daría curiosidad… Necesito que…',tip:'El interés no equivale a consentimiento. Se puede cambiar de opinión.'}]},
{id:'semana',icon:'calendar',title:'Nuestra semana',description:'Mirar lo vivido y elegir qué cuidar ahora.',category:'Conectar',minutes:7,color:'sand',basis:'Revisión semanal · Adaptación educativa',steps:[{title:'Algo que nos acercó',question:'¿Cuándo te sentiste acompañado esta semana?',placeholder:'Me sentí cerca cuando…'},{title:'Algo que costó',question:'¿Qué momento se hizo difícil, desde tu experiencia?',placeholder:'Para mí fue difícil…',tip:'No hace falta convertir la revisión en una discusión.'},{title:'Algo que repetimos',question:'¿Qué gesto pequeño merece tener espacio esta semana?',placeholder:'Me gustaría repetir…'},{title:'Un ajuste amable',question:'¿Qué podríamos cambiar para que la próxima semana sea más llevadera?',placeholder:'Podríamos probar…'}]}
];
export const DATES=[
{title:'Un paseo sin destino',minutes:20,cost:'Gratis',text:'Elegid un camino habitual y miradlo como si fuera nuevo. Cada uno señala tres cosas que nunca había notado.',question:'¿Qué te ha gustado descubrir?'},
{title:'La banda sonora de hoy',minutes:15,cost:'Gratis',text:'Cada uno elige dos canciones: una que refleje cómo llega y otra que le gustaría compartir. Escuchad sin hacer otra cosa.',question:'¿Qué te conecta con esa canción?'},
{title:'Café con una pregunta',minutes:15,cost:'En casa',text:'Preparad vuestra bebida favorita, dejad el móvil a un lado y elegid una sola pregunta de la biblioteca.',question:'¿Qué has entendido mejor del otro?'},
{title:'Una receta entre dos',minutes:40,cost:'En casa',text:'Elegid algo sencillo con lo que ya tengáis. Repartid tanto la preparación como la recogida.',question:'¿Qué parte del plan os ha resultado más agradable?'},
{title:'Dos miradas, un barrio',minutes:30,cost:'Gratis',text:'Dad un paseo. Cada persona elige una parada y explica qué le gusta de ese lugar.',question:'¿Qué lugar te gustaría volver a visitar?'},
{title:'Una tarde sin productividad',minutes:30,cost:'Gratis',text:'Reservad media hora para hacer algo que no tenga que servir para nada: dibujar, jugar o simplemente estar.',question:'¿Qué te ayuda a soltar la exigencia?'},
{title:'Una historia en cinco fotos',minutes:20,cost:'Gratis',text:'Cada uno elige cinco fotos propias que le apetezca enseñar. No tienen que ser de la relación. Contad la historia detrás.',question:'¿Qué recuerdo no conocías?'},
{title:'El plan de diez euros',minutes:45,cost:'Hasta 10 €',text:'Acordad un presupuesto máximo y un plan pequeño. Puede ser una merienda o preparar un picnic cerca de casa.',question:'¿Qué hizo especial el rato, más allá de lo que gastasteis?'},
{title:'Recrear un buen momento',minutes:30,cost:'En casa',text:'Elegid un recuerdo agradable y recuperad un detalle: la comida, la música o el juego. No hace falta copiarlo entero.',question:'¿Qué ha cambiado y qué sigue gustándoos?'},
{title:'Me enseñas, te enseño',minutes:25,cost:'Gratis',text:'Cada persona enseña algo sencillo que sabe hacer. La otra no tiene que hacerlo bien, solo probar.',question:'¿Qué te gusta de ver al otro en su elemento?'},
{title:'Un rincón más vuestro',minutes:25,cost:'En casa',text:'Elegid un espacio pequeño y hacedlo más agradable con lo que ya tenéis. Acordad qué necesita cada uno.',question:'¿Qué hace que un sitio se sienta acogedor para ti?'},
{title:'El cielo de esta noche',minutes:15,cost:'Gratis',text:'Buscad una ventana, un balcón o un lugar cómodo al aire libre. Mirad el cielo un rato sin tener que llenar el silencio.',question:'¿Cómo llegas a este momento?'}];
export const DESIRE_OPTIONS=['Pasear de la mano','Bailar en casa','Una cita sorpresa acordada','Un abrazo sin más expectativas','Un masaje de hombros','Un rato de conversación íntima','Preparar una cena juntos','Tener tiempo a solas antes de vernos','Hablar de lo que nos atrae','Un beso sin prisa'];
export const PATHS=[{id:'inicio',title:'Volver a lo sencillo',desc:'Tres momentos para recuperar la conversación.',modules:['mapa','apego','semana'],icon:'sun',color:'coral'},{id:'escucha',title:'Entendernos mejor',desc:'Expresar, escuchar y repartir con más claridad.',modules:['conflicto','equipo','reparar'],icon:'circles',color:'lavender'},{id:'propio',title:'Cerca, con espacio',desc:'Cuidar el vínculo sin perderte de vista.',modules:['autonomia','apego','deseo'],icon:'leaf',color:'sage'}];
