// A stable index of destinations: no personal answers or credentials are searched.
export const ACTIVITY_GROUPS=['Todas','Conectar','Reparar','Disfrutar','Cuidarme','Recorridos'];
export const MODULE_LABELS={mapa:['Conoceros mejor','El mundo de cada uno, más allá de cómo ha ido el día.','Conectar'],apego:['Sentirme cerca de ti','Poner palabras a lo que necesitas para sentir seguridad.','Conectar'],conflicto:['Hablar sin hacernos daño','Reconocer el conflicto y cambiar la forma de hablar.','Reparar'],reparar:['Reparar una discusión','Escuchar, asumir lo propio y volver con hechos.','Reparar'],autonomia:['Cuidar mi autonomía','Mis límites, mi autoestima y mi espacio propio.','Cuidarme'],equipo:['Repartir la carga','Hablar de las tareas y responsabilidades que no se ven.','Conectar'],deseo:['Hablar del deseo','Explorar curiosidad, cercanía y espacio personal.','Disfrutar'],semana:['Revisar nuestra semana','Qué os hizo bien y qué os gustaría ajustar.','Conectar']};
export function makeActivityIndex(modules,topics,dates,paths){return [
{id:'checkin',title:'Cómo estoy hoy',description:'Check-in de emociones y necesidades.',group:'Conectar',icon:'sun',color:'coral',action:'checkin',meta:'2 min',keywords:'animo estado triste cansancio escuchar',featured:true},
{id:'questions',title:'Preguntas para conoceros',description:'120 preguntas, por temas y sin repetición automática.',group:'Conectar',icon:'book',color:'lavender',action:'questions',meta:'12 temas',keywords:'conversar hablar intimidad juego 36 aron',featured:true},
{id:'favorites',title:'Mis preguntas favoritas',description:'Volver a las preguntas que has guardado.',group:'Conectar',icon:'star',color:'sand',action:'favorite-deck',meta:'Guardadas',keywords:'estrella marcadas guardar favoritas'},
{id:'gratitude',title:'Escribir un aprecio',description:'Agradecer un gesto que te hizo bien.',group:'Conectar',icon:'heart',color:'coral',action:'gratitude',meta:'2 min',keywords:'gracias gratitud agradecer recuerdo',featured:true},
{id:'plans',title:'Planes para dos',description:'Ideas sencillas para compartir fuera de la pantalla.',group:'Disfrutar',icon:'calendar',color:'sage',action:'plans',meta:'12 ideas',keywords:'citas salir hacer juntos diversion',featured:true},
{id:'desire-menu',title:'Coincidencias de deseo',description:'Solo se revelan los síes que ambos autoricéis.',group:'Disfrutar',icon:'spark',color:'lavender',action:'desire-direct',meta:'+18 · Por turnos',keywords:'sexo erotismo intimidad menu ciegas consentimiento',featured:true},
{id:'pause',title:'Necesito una pausa',description:'Un temporizador para bajar el ritmo.',group:'Reparar',icon:'pause',color:'sage',action:'pause',meta:'5–30 min',keywords:'calma respirar ansiedad tension parar descanso',featured:true},
{id:'journal',title:'Escribir en mi diario',description:'Poner en palabras lo que sientes o necesitas.',group:'Cuidarme',icon:'edit',color:'sage',action:'journal',meta:'A tu ritmo',keywords:'reflexion escribir notas personal',featured:true},
...modules.map(m=>({id:'module-'+m.id,title:MODULE_LABELS[m.id][0],description:MODULE_LABELS[m.id][1],group:MODULE_LABELS[m.id][2],icon:m.icon,color:m.color,action:'module',target:m.id,meta:m.minutes+' min'+(m.adult?' · +18':''),keywords:m.title+' '+m.description+' '+m.basis+(m.id==='autonomia'?' dependencia limites autoestima celos':'')+(m.id==='reparar'?' perdon mentira confianza discusion':'')+(m.id==='equipo'?' tareas casa mental responsabilidades':''),featured:true})),
...paths.map(p=>({id:'path-'+p.id,title:p.title,description:p.desc,group:'Recorridos',icon:p.icon,color:p.color,action:'path',target:p.id,meta:p.modules.length+' momentos',keywords:'recorrido guiado pasos rutina',featured:true})),
...topics.map(t=>({id:'topic-'+t[0],title:t[1],description:t[2],group:'Conectar',icon:'book',color:'lavender',action:'deck',target:t[0],meta:'10 preguntas'+(t[0]==='intimidad'?' · +18':''),keywords:'preguntas tema '+t[4].join(' ')})),
...dates.map((d,i)=>({id:'date-'+i,title:d.title,description:d.text,group:'Disfrutar',icon:'calendar',color:'sage',action:'date',target:String(i),meta:d.minutes+' min · '+d.cost,keywords:'plan cita '+d.question})),
{id:'agreements',title:'Nuestros acuerdos',description:'Propuestas, acuerdos en marcha y revisiones.',group:'Nosotros',icon:'notes',color:'coral',action:'go-agreements',meta:'Nosotros',keywords:'tareas pactos seguimiento compromisos pendientes'},
{id:'new-agreement',title:'Crear una propuesta',description:'Preparar algo concreto para acordarlo entre los dos.',group:'Nosotros',icon:'plus',color:'coral',action:'agreement',meta:'Nuevo acuerdo',keywords:'crear nuevo acuerdo propuesta compromiso'},
{id:'memories',title:'Nuestros aprecios',description:'Los agradecimientos que habéis guardado.',group:'Nosotros',icon:'heart',color:'lavender',action:'go-memories',meta:'Nosotros',keywords:'recuerdos gratitud gestos agradecimientos historial'},
{id:'history',title:'Mis reflexiones y check-ins',description:'Consultar lo que has decidido guardar.',group:'Cuidarme',icon:'notes',color:'sage',action:'my-history',meta:'Mi espacio',keywords:'historial notas diario respuestas textos registros'},
{id:'rhythm',title:'Nuestro ritmo semanal',description:'Consultar los momentos registrados esta semana.',group:'Nosotros',icon:'calendar',color:'sage',action:'rhythm',meta:'Semana',keywords:'progreso racha dias objetivo semanal'},
{id:'settings',title:'Ajustes y cuenta',description:'Nombres, apariencia, contraseña y cierre de sesión.',group:'Cuenta',icon:'settings',color:'lavender',action:'settings',meta:'Mi espacio',keywords:'oscuro claro nombre perfil cambiar contraseña login cerrar sesion'},
{id:'backup',title:'Copia de seguridad',description:'Descargar una copia cifrada del espacio.',group:'Cuenta',icon:'download',color:'sage',action:'export',meta:'Datos',keywords:'backup exportar guardar descargar'},
{id:'restore',title:'Restaurar una copia',description:'Importar un espacio después de revisarlo.',group:'Cuenta',icon:'download',color:'sage',action:'import',meta:'Datos',keywords:'recuperar backup importar movil'},
{id:'privacy',title:'Privacidad',description:'Qué se guarda, dónde y quién puede verlo.',group:'Cuenta',icon:'lock',color:'sage',action:'privacy',meta:'Datos',keywords:'seguridad cifrado datos consentimiento'},
{id:'delete-account',title:'Eliminar cuenta y datos',description:'Revisar el borrado del espacio local.',group:'Cuenta',icon:'trash',color:'coral',action:'reset',meta:'Confirmación necesaria',keywords:'borrar eliminar cuenta'},
{id:'support',title:'Necesito apoyo individual',description:'Cuando una conversación conjunta no es segura.',group:'Cuidarme',icon:'leaf',color:'sage',action:'safety',meta:'Apoyo',keywords:'miedo violencia coaccion ayuda seguridad'},
{id:'about',title:'Sobre ENTRE',description:'Qué ofrece y en qué se inspira.',group:'Cuenta',icon:'info',color:'lavender',action:'about',meta:'Información',keywords:'terapia gottman sue johnson perel aron imago fundamentos'}
]}
export const normalizeSearch=text=>String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
export function findActivities(index,query,group='Todas'){const words=normalizeSearch(query).split(/\s+/).filter(Boolean);return index.filter(e=>(group==='Todas'||e.group===group)&&words.every(w=>normalizeSearch(e.title+' '+e.description+' '+e.keywords+' '+e.meta).includes(w))).map(e=>({entry:e,score:words.reduce((n,w)=>n+(normalizeSearch(e.title).includes(w)?5:0)+(normalizeSearch(e.description).includes(w)?2:0),0)})).sort((a,b)=>b.score-a.score).map(x=>x.entry)}
